climate:
  - platform: climate_template
    name: living_room_ac
    unique_id: b7701e1e-5e74-4927-812e-68246dde8953
    icon_template: mdi:air-conditioner
    min_temp: 16
    max_temp: 30
    precision: 1.0
    temp_step: 1.0
    modes:
      - "off"
      - "auto"
      - "cool"
      - "heat"
      - "dry"
      - "fan_only"
    fan_modes:
      - "auto"
      - "low"
      - "medium"
      - "high"
    current_temperature_template: "{{ state_attr('climate.living_room_ac_mqtt', 'current_temperature') }}"
    current_humidity_template: "{{ state_attr('climate.living_room_ac_mqtt', 'current_humidity') }}"
    target_temperature_template: "{{ state_attr('climate.living_room_ac_mqtt', 'temperature') }}"
    hvac_mode_template: "{{ states('climate.living_room_ac_mqtt') }}"
    fan_mode_template: "{{ state_attr('climate.living_room_ac_mqtt', 'fan_mode') }}"
    set_temperature:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac_switchbot
        data:
          temperature: "{{ temperature }}"
    set_hvac_mode:
      - choose:
        - conditions:
            condition: template
            value_template: "{{ hvac_mode == 'off' }}"
          sequence:
            action: switch.turn_off
            target:
              entity_id: switch.living_room_ac_switchbot
        - conditions:
            condition: template
            value_template: "{{ hvac_mode == 'auto' }}"
          sequence:
            action: climate.set_hvac_mode
            target:
              entity_id: climate.living_room_ac_switchbot
            data:
              hvac_mode: "heat_cool"
        default:
            action: climate.set_hvac_mode
            target:
              entity_id: climate.living_room_ac_switchbot
            data:
              hvac_mode: "{{ hvac_mode }}"
    set_fan_mode:
      - action: climate.set_fan_mode
        target:
          entity_id: climate.living_room_ac_mqtt
        data:
          fan_mode: "{{ fan_mode }}"

homeassistant:
  customize:
    climate.living_room_ac:
      friendly_name: リビング エアコン